import{summarize,i18n,DB_KEY}from"../js/cllama.js";import{balert}from"../js/dialog.mjs";import{marked}from"../js/marked.mjs";import{copyToClipboard,thinkCollapseExpanded}from"../js/marked/copy.mjs";import{addClass,hasClass,removeClass,replaceElementContent,replaceThinkTags,sendToContentScript}from"../js/util.js";let browser="undefined"!=typeof chrome?chrome:browser,isFirefox=0<=navigator.userAgent.indexOf("Firefox");document.addEventListener("DOMContentLoaded",()=>{let l=document.getElementById("summaryList"),r=document.getElementById("actions"),n=[],d=new DOMParser;function c(e){return`
    <div class="summary-card mb-2">
        <a href="#" data-href="${e.url}" class="entry-title" title="${e.title}">${e.title}</a>
        <div id="${e.msgId}" class="insightifyHBody summary-content markdown-body">${marked.parse(e.content)}</div>
        <div class="row insightifyHBody">
          <div class="col">
            <small class="timestamp">${e.ctime.split(" ")[0]} ${e.ctime.split(" ")[1]}</small>
          </div>
          <div class="col">
            <a href="#" data-id="${e.msgId}" class="trash text-end"><svg class="bi me-2" style="height:0.85em;"><use href="#svg_trash"></use></svg></a>
          </div>
        </div>
    </div>
    `}function m(e,r){copyToClipboard(r),thinkCollapseExpanded(r);{var s=r,a=s.querySelector(".trash");let t=a.getAttribute("data-id");a.style.display="block",a.addEventListener("click",async e=>{n=n.filter(e=>e.msgId!=t),await browser.storage.local.set({[DB_KEY.insightList]:n}),s.remove(),e.preventDefault()})}{a=e;var i=r;let t=i.querySelector("a.entry-title");a||(i.querySelectorAll(".insightifyHBody").forEach(e=>e.style.display="none"),addClass(t,"title-mask")),t.addEventListener("click",e=>{hasClass(t,"title-mask")?(i.querySelectorAll(".insightifyHBody").forEach(e=>e.style.display=""),removeClass(t,"title-mask")):browser.tabs.create({url:t.getAttribute("data-href")}),e.preventDefault()})}}browser.storage.local.get(DB_KEY.insightList,function(e){(n=e[DB_KEY.insightList]||[])&&n.forEach(e=>{e=replaceThinkTags(c(e)),e=d.parseFromString(e,"text/html").body.firstChild.cloneNode(!0);m(!1,e),l.insertBefore(e,l.children[0])})}),browser.storage.local.get(DB_KEY.actionList,function(e){let t=e[DB_KEY.actionList];(!t||t.length<1)&&(t=[{id:1,name:browser.i18n.getMessage("summarizer"),prompt:browser.i18n.getMessage("summaryPrompt").replaceAll("{localLanguage}",browser.i18n.getMessage("localLanguage"))}],browser.storage.local.set({[DB_KEY.actionList]:t})),t.forEach(e=>{var i=e,e=`<a id="ac_${i.id}" href="#" class="btn btn-sm btn-outline-primary b_action i18n">${i.name}</a>`,o=(e=d.parseFromString(e,"text/html"),r.appendChild(e.body.firstChild.cloneNode(!0)),document.getElementById("ac_"+i.id));o.addEventListener("click",()=>{sendToContentScript({action:"getPageInfo"}).then(e=>{var r,t,s,a;e&&e.title&&e.content?(addClass(o,"disabled"),r="msg_"+(new Date).getTime(),s="<strong>"+browser.i18n.getMessage("waitMessage")+"</strong>",s=c(t={url:e.url,title:i.name+" : "+e.title.replaceAll('"',"'"),content:s,ctime:(new Date).toLocaleString(),msgId:r}),a=d.parseFromString(s,"text/html").body.firstChild.cloneNode(!0),l.insertBefore(a,l.children[0]),summarize(i.prompt,e,r,{finish:function(e){t.content=e,100<=n.length&&n.shift(),n.push(t),browser.storage.local.set({[DB_KEY.insightList]:n}),removeClass(o,"disabled"),m(!0,a)},error:function(e,t){removeClass(o,"disabled"),"AbortError"!==e.name&&(console.error("summarize error:",e),replaceElementContent(document.getElementById(r),browser.i18n.getMessage("cllamaError")))}}).catch(e=>{console.error("summarize error:",e),replaceElementContent(document.getElementById(r),browser.i18n.getMessage("cllamaError")),removeClass(o,"disabled")})):balert(browser.i18n.getMessage("insightifyPageError1"))}).catch(function(e){balert(browser.i18n.getMessage("insightifyPageError2")),console.log(e)})})})}),i18n()});export{browser,isFirefox};