import{i18n,DB_KEY}from"../js/cllama.js";import{marked}from"../js/marked.mjs";import{getLanguageCode,htmlEncode,replaceElementContent}from"../js/util.js";document.addEventListener("DOMContentLoaded",()=>{let o="undefined"!=typeof chrome?chrome:o;var e=0<=navigator.userAgent.indexOf("Firefox");let a=document.getElementById("config-list"),l=new bootstrap.Modal(document.getElementById("addConfigModal")),n=o.i18n.getMessage("wordsRemaining"),m=[],d=new DOMParser;function r(){document.querySelectorAll("#name, #prompt, #sample").forEach(t=>{let a=t.closest(".mb-3").querySelector(".character-counter");var e=()=>{var e=t.getAttribute("maxlength")-t.value.length;a.textContent=n+"："+e,a.style.color=e<10?"#dc3545":"#6c757d"};t.addEventListener("input",e),e()})}function s(){document.getElementById("add-config-form").reset(),document.querySelectorAll(".character-counter").forEach(e=>e.textContent="")}function i(t){var e=(e=>(e.sample||(e.sample=""),`
            <div class="col-12" id="sp_${e.id}">
                <div class="config-card card mb-3">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-start">
                            <div>
                                <h3 class="card-title">${e.name}</h3>
                                <div class="card-text text-muted card-cust-height markdown-body">${htmlEncode(e.prompt)}</div>
                                <div class="card-sample">${e.sample}</div>
                            </div>
                            <div class="btn-group">
                                <button class="btn btn-sm btn-outline-secondary">✘</button>
                                <button class="btn btn-sm btn-outline-secondary">✍</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        `))(t),e=d.parseFromString(e,"text/html").body.firstChild.cloneNode(!0);e.getElementsByTagName("button")[0].addEventListener("click",()=>{m=m.filter(e=>e.id!=t.id),document.getElementById("sp_"+t.id).remove(),o.storage.local.remove("chatHistory_"+t.id),o.storage.local.set({[DB_KEY.chatTpaList]:m})}),e.getElementsByTagName("button")[1].addEventListener("click",()=>{s(),document.getElementById("aidId").value=t.id,document.getElementById("name").value=t.name,document.getElementById("prompt").value=t.prompt,document.getElementById("sample").value=t.sample||"",l.show(),setTimeout(r,100)}),a.appendChild(e)}document.getElementById("save-config-btn").addEventListener("click",()=>{let t=+document.getElementById("aidId").value.trim();var a=document.getElementById("name").value.trim(),n=document.getElementById("prompt").value.trim(),d=document.getElementById("sample").value.trim();if(0<a.length&&1<n.length){if(0<t){var e=m.find(e=>e.id===t);e?(e.name=a,e.prompt=n,e.sample=d||"",(e=document.getElementById("sp_"+t))&&(e.getElementsByClassName("card-title")[0].innerText=a,replaceElementContent(e.getElementsByClassName("card-text")[0],n),e.getElementsByClassName("card-sample")[0].innerText=d)):alert(o.i18n.getMessage("noUpdateDataError"))}else{let e={id:Date.now(),name:a,prompt:n,sample:d};m.push(e),i(e)}o.storage.local.set({[DB_KEY.chatTpaList]:m}),l.hide(),s()}else alert(o.i18n.getMessage("requiredError"))}),document.getElementById("add-config-btn").addEventListener("click",()=>{s(),document.getElementById("aidId").value="",l.show(),setTimeout(r,100)}),o.storage.local.get(DB_KEY.chatTpaList,function(e){for(var t of m=(m=e[DB_KEY.chatTpaList])||[])i(t)}),i18n(),e?document.getElementById("b_import").setAttribute("href","https://fxdq.net/"+getLanguageCode()+"/aidir.html"):document.getElementById("b_import").addEventListener("click",e=>{o.tabs.create({url:"https://fxdq.net/"+getLanguageCode()+"/aidir.html"}),e.preventDefault()}),o.runtime.onMessage.addListener((e,t,a)=>("callImportAIdirPrompt"===e.action&&a({success:!0,data:(e=>{var t={id:t=Date.now(),name:e.name,prompt:e.prompt,sample:e.sample};return e.metac&&1<e.metac.length&&(t.metac=e.metac),m.push(t),i(t),window.scrollTo(0,document.body.scrollHeight),o.storage.local.set({[DB_KEY.chatTpaList]:m}),e.sid})(e.data)}),!0))});